name: alexandra
version: "1.1"
summary: Amazon Alexa snap
description: Add Amazon Alexa to your device
confinement: strict

apps:
  alexa:
    command: bin/alexa.py
    daemon: simple
    plugs: [network, network-bind, pulseaudio]
  alexa-run:
    command: bin/alexa.py
    plugs: [network, network-bind, pulseaudio]

parts:
  python-hyper:
    plugin: python
    python-version: python3
    python-packages: [requests, 'git+https://github.com/moaxey/python-zeroconf', pocketsphinx]
  pyalexa:
    plugin: dump
    source: ..
    organize:
      alexa.py: bin/alexa.py
      alexa_audio.py: bin/alexa_audio.py
      alexa_audio_device.py: bin/alexa_audio_device.py
      alexa_audio_device_pulse.py: bin/alexa_audio_device_pulse.py
      alexa_auth.py: bin/alexa_auth.py
      alexa_control.py: bin/alexa_control.py
      alexa_device.py: bin/alexa_device.py
      alexa_http_config.py: bin/alexa_http_config.py
      alexa_params.py: bin/alexa_params.py
    stage-packages:
      - ffmpeg
      - libpulse0
      - pulseaudio
    build-packages:
      - swig
      - git
      - libpulse-dev

